In [8]:
from src.parser_files import get_letters
import numpy as np
from src.plots import *
import pandas as pd
import itertools

letters = get_letters("data/letters.txt")

letters_dict = {}
current_letter = 65
for letter in letters:
    letters_dict[chr(current_letter)] = letter
    current_letter += 1

all_groups = list(itertools.combinations(letters_dict.keys(), r=4))
avg_dot_product = []
max_dot_product = []

for i in range(len(all_groups)):
    group = np.array([v for k,v in letters_dict.items() if k in all_groups[i]])
    orto_matrix = group.dot(group.T)
    np.fill_diagonal(orto_matrix, 0)
    #print(f'{all_groups[i]}\n{orto_matrix}\n-------------------------------------')
    row, _ = orto_matrix.shape
    avg_dot_product.append((np.abs(orto_matrix).sum() / (orto_matrix.size - row), all_groups[i]))
    max_v = np.abs(orto_matrix).max()
    max_dot_product.append(((max_v, np.count_nonzero(np.abs(orto_matrix) == max_v) / 2), all_groups[i]))

df = pd.DataFrame(sorted(avg_dot_product), columns=["|<,>| medio", "grupo"])
df.head(15).style.format({'|<,>| medio': "{:.2f}"}).hide(axis='index')

('A', 'B', 'C', 'D')
[[ 0 15  7  9]
 [15  0  9 19]
 [ 7  9  0 15]
 [ 9 19 15  0]]
-------------------------------------
('A', 'B', 'C', 'E')
[[ 0 15  7 13]
 [15  0  9 15]
 [ 7  9  0 19]
 [13 15 19  0]]
-------------------------------------
('A', 'B', 'C', 'F')
[[ 0 15  7 17]
 [15  0  9 11]
 [ 7  9  0 11]
 [17 11 11  0]]
-------------------------------------
('A', 'B', 'C', 'G')
[[ 0 15  7 15]
 [15  0  9 17]
 [ 7  9  0 17]
 [15 17 17  0]]
-------------------------------------
('A', 'B', 'C', 'H')
[[ 0 15  7 19]
 [15  0  9  9]
 [ 7  9  0  1]
 [19  9  1  0]]
-------------------------------------
('A', 'B', 'C', 'I')
[[ 0 15  7 -1]
 [15  0  9  1]
 [ 7  9  0 13]
 [-1  1 13  0]]
-------------------------------------
('A', 'B', 'C', 'J')
[[ 0 15  7  1]
 [15  0  9  3]
 [ 7  9  0 11]
 [ 1  3 11  0]]
-------------------------------------
('A', 'B', 'C', 'K')
[[ 0 15  7  7]
 [15  0  9 -3]
 [ 7  9  0  5]
 [ 7 -3  5  0]]
-------------------------------------
('A', 'B', 'C', 'L')
[[ 0 15  7 -1]
 [15

In [3]:
df.tail(15).style.format({'|<,>| medio': "{:.2f}"}).hide(axis='index')

In [4]:
df2 = pd.DataFrame(sorted(max_dot_product), columns=["|<,>| max", "grupo"])
df2.head(15).style.format({'|<,>| max': lambda x: 'max: {:,.0f} | count: {:,.0f}'.format(*x)}).hide(axis='index')

In [5]:
df3 = df2.merge(df)
df3 = df3[['|<,>| max', '|<,>| medio', 'grupo']]
df3.head(10).style.format({'|<,>| max': lambda x: 'max: {:,.0f} | count: {:,.0f}'.format(*x), '|<,>| medio': "{:.2f}"}).hide(axis='index')

In [7]:
df3.tail(10).style.format({'|<,>| max': lambda x: 'max: {:,.0f} | count: {:,.0f}'.format(*x), '|<,>| medio': "{:.2f}"}).hide(axis='index')